[project]
name = "data-archive"
version = "0.1.0"
description = "A collection of (semi)automated open data snapshots."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "polars>=1.37.1",
    "requests>=2.32.5",
]
